bazel_dep(name = "bazel_skylib", version = "1.9.2")
bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "rules_cc", version = "0.2.25")
bazel_dep(name = "rules_python", version = "2.3.4")

rules_python_config = use_extension("@rules_python//python/extensions:config.bzl", "config")
rules_python_config.explicit_init_py(default = True)

bazel_dep(name = "rules_shell", version = "0.8.0")

# The tansitively resolved version is not Bazel 9.2.0 compatible.
# ERROR: Traceback (most recent call last):
#         File "external/aspect_bazel_lib++toolchains+copy_directory_toolchains/defs.bzl", line 15, column 20, in <toplevel>
#                 resolved_toolchain = rule(
# Error in rule: rule() got unexpected keyword argument 'incompatible_use_toolchain_transition'
single_version_override(
    module_name = "aspect_bazel_lib",
    version = "2.22.5",
)

# The tansitively resolved version is not Bazel 9.2.0 compatible.
# ERROR: Traceback (most recent call last):
#         File "external/rules_nodejs++node+nodejs_toolchains/defs.bzl", line 15, column 20, in <toplevel>
#                 resolved_toolchain = rule(
# Error in rule: rule() got unexpected keyword argument 'incompatible_use_toolchain_transition'
single_version_override(
    module_name = "rules_nodejs",
    version = "6.7.5",
)

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "bin",
    build_file_content = """
load("@bazel_skylib//rules:native_binary.bzl", "native_binary")

native_binary(
    name = "Ruff",
    src = "ruff",
    out = "ruff",
    visibility = ["//visibility:public"],
)
    """,
    integrity = "sha256-4uVMPHDD9r+BAasuTLLRSuvabY7LqGIr0cziI3hkHsw=",
    url = "https://github.com/astral-sh/ruff/releases/download/v0.0.272/ruff-x86_64-unknown-linux-gnu.tar.gz",
)

register_toolchains(
    "//toolchain:ruff_toolchain",
)

bazel_dep(name = "inner")
local_path_override(
    module_name = "inner",
    path = "inner",
)
