module(
    name = "inner",
)

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

bazel_dep(name = "rules_cc", version = "0.2.8")
bazel_dep(name = "aspect_rules_lint", version = "1.9.0")
bazel_dep(name = "bazel_skylib", version = "1.8.2")


http_archive(
    name = "clang",
    url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/clang+llvm-18.1.8-x86_64-linux-gnu-ubuntu-18.04.tar.xz",
    strip_prefix = "clang+llvm-18.1.8-x86_64-linux-gnu-ubuntu-18.04",
    integrity = "sha256-VOwwNYr8yfuKp0MH2zBG9Rh/n7ifs3Bkzd6QbgYuvzY=",
    build_file_content = """
load("@bazel_skylib//rules:native_binary.bzl", "native_binary")
native_binary(
    name = "clang-tidy",
    src = "bin/clang-tidy",
    out = "clang-tidy",
    visibility = ["//visibility:public"],
)
    """,
    patch_cmds = [
        """echo 'bazel_dep(name = "bazel_skylib", version = "1.7.1")' >> MODULE.bazel""",
    ],
)
